remote_theme: just-the-docs/just-the-docs
color_scheme: "dark"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"

nav_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"